#!/bin/bash

set -euo pipefail

# Домен
DOMAIN="rea26.skills"

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}


check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "Этот скрипт должен быть запущен от root"
        exit 1
    fi
}

show_help() {
    cat << EOF
Использование: $(basename "$0") <short_hostname>

Скрипт для предварительной настройки Linux машины.
Домен: $DOMAIN

Поддерживаемые серверы:
  br-srv1     192.168.1.10/24   br-srv1.$DOMAIN
  br-srv2     192.168.1.20/24   br-srv2.$DOMAIN
  br-srv3     192.168.1.30/24   br-srv3.$DOMAIN
  br-dc       192.168.1.50/24   br-dc.$DOMAIN
  br-cli      192.168.3.50/24   br-cli.$DOMAIN
  cr-dc       192.168.2.50/24   cr-dc.$DOMAIN
  cr-srv      192.168.2.100/24  cr-srv.$DOMAIN
  win-ad      192.168.2.90/24   win-ad.$DOMAIN
  cr-cli      192.168.4.50/24   cr-cli.$DOMAIN
  out-cli     192.168.122.10/24 out-cli.$DOMAIN
  isp-srv     -                 isp.$DOMAIN

Примеры:
  $(basename "$0") br-srv1
  $(basename "$0") cr-dc

EOF
}


setup_network() {
    local short_hostname="$1"
    local fqdn="${short_hostname}.${DOMAIN}"
    local ip_address=""
    local gateway=""
    local netmask="255.255.255.0"
    local iface=""
    local dns1="192.168.1.50"   # br-dc как DNS
    local dns2="192.168.2.50"   # cr-dc как резервный DNS
    
    # Определение параметров сети на основе hostname
    case "$short_hostname" in
        # === Branch сеть 192.168.1.0/24 ===
        br-srv1)
            ip_address="192.168.1.10"
            gateway="192.168.1.1"
            iface="enp1s0"
            ;;
        br-srv2)
            ip_address="192.168.1.20"
            gateway="192.168.1.1"
            iface="enp1s0"
            ;;
        br-srv3)
            ip_address="192.168.1.30"
            gateway="192.168.1.1"
            iface="ens192"
            ;;
        br-dc)
            ip_address="192.168.1.50"
            gateway="192.168.1.1"
            iface="ens192"
            ;;
        # === Branch клиенты 192.168.3.0/24 ===
        br-cli)
            ip_address="192.168.3.50"
            gateway="192.168.3.1"
            iface="ens192"
            ;;
        # === Core сеть 192.168.2.0/24 ===
        cr-dc)
            ip_address="192.168.2.50"
            gateway="192.168.2.1"
            iface="eth0"
            ;;
        cr-srv)
            ip_address="192.168.2.100"
            gateway="192.168.2.1"
            iface="eth0"
            ;;
        win-ad)
            ip_address="192.168.2.90"
            gateway="192.168.2.1"
            iface="enp1s0"
            ;;
        # === Core клиенты 192.168.4.0/24 ===
        cr-cli)
            ip_address="192.168.4.50"
            gateway="192.168.4.1"
            iface="ens192"
            ;;
        # === Outside 192.168.122.0/24 ===
        out-cli)
            ip_address="192.168.122.10"
            gateway="192.168.122.2"
            iface="eth0"
            dns1="8.8.8.8"
            dns2="8.8.4.4"
            ;;
        # === ISP ===
        isp-srv)
            log_warning "ISP-SRV требует ручной настройки сети"
            return 0
            ;;
        *)
            log_error "Сетевые настройки для $short_hostname не определены"
            return 1
            ;;
    esac
    
    log_info "Настройка /etc/network/interfaces для $fqdn"
    log_info "  IP: $ip_address/$netmask"
    log_info "  Gateway: $gateway"
    log_info "  Interface: $iface"
    
    cat > /etc/network/interfaces << EOF
# This file is auto-generated by common_settings.sh
# Host: $fqdn

# Loopback interface
auto lo
iface lo inet loopback

# Primary network interface - $iface
auto $iface
iface $iface inet static
    address $ip_address
    netmask $netmask
    gateway $gateway
    dns-nameservers $dns1 $dns2
    dns-search $DOMAIN
EOF
    
    log_success "Сетевой интерфейс настроен: $ip_address на $iface"
}


setup_hosts() {
    local short_hostname="$1"
    local fqdn="${short_hostname}.${DOMAIN}"
    
    log_info "Настройка /etc/hosts"
    
    cat > /etc/hosts << EOF
127.0.0.1       localhost
127.0.1.1       $fqdn $short_hostname

# Branch servers
192.168.1.10    br-srv1.$DOMAIN br-srv1
192.168.1.20    br-srv2.$DOMAIN br-srv2
192.168.1.30    br-srv3.$DOMAIN br-srv3
192.168.1.50    br-dc.$DOMAIN br-dc

# Core servers
192.168.2.50    cr-dc.$DOMAIN cr-dc
192.168.2.90    win-ad.$DOMAIN win-ad
192.168.2.100   cr-srv.$DOMAIN cr-srv

# Clients
192.168.3.50    br-cli.$DOMAIN br-cli
192.168.4.50    cr-cli.$DOMAIN cr-cli

# IPv6
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
EOF
    
    log_success "/etc/hosts настроен"
}


setup_hostname() {
    local short_hostname="$1"
    local fqdn="${short_hostname}.${DOMAIN}"
    
    log_info "Устанавливаю hostname: $fqdn"
    
    hostnamectl set-hostname "$fqdn"
    
    log_success "Hostname установлен: $fqdn"
}


setup_apt_proxy() {
    log_info "Настройка apt proxy"
    
    cat > /etc/apt/apt.conf.d/90-proxy.conf << 'EOF'
Acquire::http::Proxy "http://proxy.tech.skills:3128";
Acquire::https::Proxy "http://proxy.tech.skills:3128";
EOF
    
    log_success "Apt proxy настроен: proxy.tech.skills:3128"
}


setup_base() {
    local short_hostname="$1"
    local fqdn="${short_hostname}.${DOMAIN}"
    
    log_info "Выполняю базовую настройку для: $fqdn"
    
    # Установка имени хоста
    setup_hostname "$short_hostname"
    
    # Настройка /etc/hosts
    setup_hosts "$short_hostname"
    
    # Настройка сети
    setup_network "$short_hostname"
    
    # Настройка apt proxy
    setup_apt_proxy
    
    # Обновление системы
    log_info "Обновление списка пакетов..."
    # apt-get update -y
    
    # Установка базовых утилит
    log_info "Установка базовых утилит..."
    # apt-get install -y curl wget vim htop net-tools dnsutils
    
    # Настройка временной зоны
    log_info "Настройка временной зоны..."
    # timedatectl set-timezone Europe/Moscow
    
    log_success "Базовая настройка завершена для $fqdn"
}


configure_by_hostname() {
    local short_hostname="$1"
    
    # Сначала выполняем базовую настройку
    setup_base "$short_hostname"

    # Затем специфичную настройку в зависимости от типа хоста
    case "$short_hostname" in
        br-dc|cr-dc)
            # setup_dc "$short_hostname"
            log_info "Требуется дополнительная настройка DC"
            ;;
        br-srv*|cr-srv)
            # setup_server "$short_hostname"
            log_info "Требуется дополнительная настройка сервера"
            ;;
        win-ad)
            log_info "Windows AD - только базовая сетевая настройка"
            ;;
        *-cli)
            log_info "Клиентская машина - базовая настройка завершена"
            ;;
        *)
            log_warning "Неизвестный тип хоста: $short_hostname"
            ;;
    esac
}


main() {
    if [[ $# -lt 1 ]]; then
        log_error "Не указано имя хоста"
        show_help
        exit 1
    fi
    
    local short_hostname="$1"
    
    if [[ "$short_hostname" == "-h" || "$short_hostname" == "--help" ]]; then
        show_help
        exit 0
    fi
    
    check_root
    
    log_info "=========================================="
    log_info "Начало настройки: ${short_hostname}.${DOMAIN}"
    log_info "=========================================="
    
    configure_by_hostname "$short_hostname"
    
    log_info "=========================================="
    log_success "Настройка завершена!"
    log_info "Перезагрузите сеть: systemctl restart networking"
    log_info "=========================================="
}

main "$@"
